### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by danielhanzs** [DevWurm/angular-2-electron-seed#1]
Unable to find Electron app at D:\laragon\www\ng2-electron

Cannot find module 'D:\laragon\www\ng2-electron'

while running the npm run run
also got this wile packaging the app for windows and the package name will be $npm_package_name-$npm_package_version I think it is not declared somewhere.

[npm-debug.txt](https://github.com/DevWurm/angular-2-electron-seed/files/711498/npm-debug.txt)

**Comment by danielhanzs** [comment]
Sorry

Hi and also thank you for replying :)

**Comment by danielhanzs** [comment]
npm run run -> "start": "electron ./dist/entry.js", so the netry.js will be the main because no package.json found there

**Comment by DevWurm** [comment]
Hi :)
Did it work for you or are there any remaining issues?

**Comment by danielhanzs** [comment]
Hi only $npm_package_name-$npm_package_version folder name but I deleted that part of the code.

Thank you
