### ISSUE TITLE
CSS file not loading

### ISSUE THREAD

**Issue by sekar-worx** [DevWurm/angular-2-electron-seed#11]
Hi,
 I am facing issue like individual component css files not loading. Only the style.css file loading. I don't know how to fix it ?. 
Please help me in this

**Comment by DevWurm** [comment]
So, I can't reproduce your issue. You may need to provide more information or a sample project.

**Comment by sahiliotasol** [comment]
Hi
I think you need to add "  encapsulation: ViewEncapsulation.None" in the component as per below
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./scss/application.scss'],
  encapsulation: ViewEncapsulation.None
})

or directly give the path in angular-cli.json

"styles": [
        "styles.css"
      ],
