### ISSUE TITLE
npm run package:linux

### ISSUE THREAD

**Issue by sekar-worx** [DevWurm/angular-2-electron-seed#12]
After took the build for linux, the build is not working. It is returning error like 

**> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module '/home/packages/1.0.0-linux-x64/resources/app/dist/entry.js'
>     at Module._resolveFilename (module.js:470:15)
>     at Function.Module._resolveFilename (/home/packages/1.0.0-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:418:25)
>     at Object.<anonymous> (/home/packages/1.0.0-linux-x64/resources/electron.asar/browser/init.js:171:8)
>     at Object.<anonymous> (/homepackages/1.0.0-linux-x64/resources/electron.asar/browser/init.js:173:3)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>**

**Comment by DevWurm** [comment]
Please provide more information about your setup, how you package and how you call the package

**Comment by sekar-worx** [comment]
I am using your angular-electron-seed project as base while i took the build using npm run package:linux in ubuntu gnome 17.04 laptop it returns the above error. In live reload the app working fine. when i getting this error means once i took the build. After then i run packagename executable file but it is not executing. So, i run this file using terminal ./packagename executable file then it returns above error.

**Comment by DevWurm** [comment]
Please go into a clean directory and execute the following commands:
```sh
git clone git@github.com:DevWurm/angular-electron-seed
cd angular-electron-seed
npm install
npm run build
npm run package:linux
./packages/angular-electron-seed-0.0.0-linux-x64/angular-electron-seed-0.0.0
```

**Comment by sekar-worx** [comment]
It's working. Thank you very much
