### ISSUE TITLE
How can we use Autoupdate here to release update of code by resolving some issues and integrating some new features

### ISSUE THREAD

**Issue by sahiliotasol** [DevWurm/angular-2-electron-seed#14]
How can we use Autoupdate here to release update of code by resolving some issues and integrating some new features?

I need to release update to existing packages.

how can I do it?
I just checked on Electron site and found some ways for auto update integration as per following link
https://electron.atom.io/docs/api/auto-updater/

**Comment by DevWurm** [comment]
I have not used auto updates in Electron yet, so unfortunately I can't help you. If you find a solution, feel free to post it into this thread.
