### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by cloud602** [DevWurm/angular-2-electron-seed#2]
I clone this seed and run {npm install,npm run build,npm run run}
then Error
![image](https://cloud.githubusercontent.com/assets/5212357/22678653/9a4067f2-ed36-11e6-9876-44b6d24b06f0.png)

**Comment by DevWurm** [comment]
This occured because there was no `main` field set in the `package.json`. I fixed this and you can update your repo
```sh
git fetch
git reset origin/master --hard
```
will do this.

**Comment by cloud602** [comment]
at first,thank you very much!but i have some other problems.
my dev platform is win7 x64 and i am in china.so when i run cnpm install
![image](https://cloud.githubusercontent.com/assets/5212357/22722830/8791c470-edf4-11e6-9cac-bcafabc33d92.png)
so i cancel it and run cnpm install again.
update you source code ,run cnpm build & cnpm run run is ok now.
but i run cnpm run start ,window is ok,but web app not work.
![image](https://cloud.githubusercontent.com/assets/5212357/22722880/ec2573a0-edf4-11e6-879b-2549814c2c96.png)
at last,when i run cnpm run package:win,is slowly
![image](https://cloud.githubusercontent.com/assets/5212357/22722903/24dd9b1e-edf5-11e6-8309-9ba4faa2a113.png)
can you help me ?

**Comment by DevWurm** [comment]
So everything on your system is ok. The app is **not intended** to run in the web browser. It will only work in the electron window. This is a seed for an Angular 2 **Electron** App, not for an Angular 2 Web App. If you want to read more about the details of the configuration, you can read [this article](https://www.sogehtsoftware.de/blog/post/building-cross-platform-desktop-apps-with-angular-2-and-electron) of mine.

**Comment by cloud602** [comment]
Thanks for your reply! I have solved the problem, it's that the angular-cli hasn't installed correctly. Then I used VPN to install angular-cli. Thank you again for your article about electron's configuration.
