### ISSUE TITLE
Using scss for global styles

### ISSUE THREAD

**Issue by ydagana** [DevWurm/angular-2-electron-seed#8]
Hi, 

First off, thanks for this repo, it's really helpful. Though I'm having a hard time getting global styles to work.

for now, on my angular-cli.json file, I'm adding a bunch of styles (both css and scss)
`"styles": [
        "../node_modules/devextreme/dist/css/dx.common.css",
        "../node_modules/devextreme/dist/css/dx.light.css",
        "../node_modules/dragula/dist/dragula.min.css",
        "../node_modules/angular2-toaster/toaster.css",
        "scss/style.scss"
      ],`

I'm not sure what's the right thing to put in webpack.config.json for `entry.styles` and what to include/exclude in `module.rules`. So far everything I tried doesn't seem to work.

Let me know if you have any input, and thanks in advance.

**Comment by pedro-gorrinDNC** [comment]
im having the same issue, Everything is working except scss styles...

Thanks in advance!

**Comment by DevWurm** [comment]
You can just rename the `styles.css`  to `styles.scss` and replace all occurences of the old name in the `webpack.config.js` with the new name.
If you have multiple global styles you might want to import them into the global stylesheet via `@import`.
You can find a working example at e40c4dee3619f068800a112a03d39df31ce8d188

**Comment by DevWurm** [comment]
@ydagana @pedro-gorrinDNC can you provide some information, if this solved your problem?

**Comment by DevWurm** [comment]
@ydagana @pedro-gorrinDNC if you don't have any more problems I will close this issue.
